[package] # TODO: Remove unnecessary fields
name = "rust-core"
version = "1.0.0"
edition = "2024"
authors = ["Mr Richardson"]
description = "Easily construct your robots drive-path in the digital world."
documentation = "https://docs.rs/autonomous_path_architect" # TODO: write docs and set up docs.rs
readme = "README.md" # TODO: Write proper readme
license = "GNU General Public License v3.0"
repository = "https://github.com/Mr-Richardson/autonomous_path_architect"
keywords = ["robotics", "macroquad", "tool"]
categories = ["science::robotics", "simulation", "rendering::engine"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
glam = "0.33.2"
wasm-bindgen = "0.2"
ruff_python_parser = "0.0.11"
ruff_python_ast = "0.0.11"
