[package]
name = "autonomous_path_architect"
version = "0.0.1"
edition = "2024"
authors = ["Mr Richardson"]
description = "Easily construct your robots drive-path in the digital world."
documentation = "https://docs.rs/autonomous_path_architect" # TODO verify
readme = "README.md"
license = "GNU General Public License v3.0"
repository = "https://github.com/Mr-Richardson/autonomous_path_architect"
keywords = ["robotics", "macroquad", "tool"]
categories = ["science::robotics", "simulation", "rendering::engine"]

[dependencies]
button_lib = { git = "https://github.com/Mr-Richardson/macroquad_button_lib" }
macroquad = "0.4.15"